In [1]:
# Stiffness method

We will use NumPy to store the stiffness matrix and the force vector, and compute the displacement vector:

In [2]:
import numpy as np
from numpy.linalg import inv

Define the stiffness matrix after removing the first row and the first column:

In [3]:
K = np.matrix('5 -3; -3 6')
print(K)

[[ 5 -3]
 [-3  6]]


Define the force vector, at node 0, the force is 0 and at node 3 we apply a unit force.

In [4]:
b = np.matrix('0; 1')
print(b)

[[0]
 [1]]


To calculate the displacement, our governing equation is: $\mathbf{Ku} = \mathbf{b}$, to find $\mathbf{u}$ we do $\mathbf{u} = \mathbf{K}^{-1}\mathbf{b}$. 

This gives us the displacements at nodes 2 and 3:

In [5]:
u = inv(K)*b
print(u)

[[0.14285714]
 [0.23809524]]
